import Head from 'next/head'
import Image from 'next/image'
/* components */
import Link from '../components/Link'

const Home = () => {
  return (
    <div>
      <Head>
        <title>Gift Innovation 合同会社</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="background-image grid grid-cols-1 m-auto">
        <div className="flex text-gray-100 pt-10">
          <div className="m-auto pt-4 pb-16 sm:m-auto w-4/5 block text-center">
            <h1 className="sm:text-white text-5xl uppercase font-bold text-shadow-md pb-14">
              Gift Inovvation 合同会社
            </h1>
            <Link
              href="/blog"
              className="text-center bg-gray-50 text-gray-700 py-2 px-4 font-bold text-xl uppercase"
            >
              Read more
            </Link>
          </div>
        </div>
      </div>

      <div className="sm:grid grid-cols-2 gap-20 w-4/5 mx-auto py-15 border-b border-grat-200">
        <div>
          <Image src="/images/gift_wire.jpg" width="700" height="400" alt="" />
        </div>
        <div className="m-auto sm:m-auto text-left w-4/5 block">
          <h2 className="text-3xl font-extrabold text-gray-600">
            Gift 王寺駅前自習室
          </h2>
          <p className="py-8 text-gray-500 text-l">
            ～志のある人を応援するプロジェクト～
          </p>
          <p className="font-extrabold text-gray-600 text-l pb-9">
            Lurem ipsum, dolor sit amet consectetur adipisicing elit. Sapiente
            magnam vero nostrum! Perferendis eos molestias porrp vero. Vel
            alias.
          </p>
          <Link
            href="/blog"
            className="uppercase bg-blue-500 text-gray-100 text-s font-extrabold py-3 px-8 rounded-3xl"
          >
            Find Out More
          </Link>
        </div>
      </div>

      <div className="text-center p-15">
        <h2 className="py-10 text-4xl font-bold">Recent Post</h2>
      </div>

      <div className="w-4/5 grid-cols-2 m-auto sm:grid">
        <div className="flex pt-10 text-gray-100 bg-gray-400">
          <div className="block w-4/5 pt-4 pb-16 m-auto sm:m-auto">
            <h2 className="pb-16 text-5xl font-bold text-gray-700"></h2>
            <Link
              href="blog?page=1"
              className="px-5 py-3 text-xs font-extrabold uppercase bg-transparent border-2 border-gray-100 rounded-3xl"
            >
              Find Out More
            </Link>
          </div>
        </div>
        <div>
          <Image src="/images/gift_wire.jpg" width="700" height="400" alt="" />
        </div>
      </div>
    </div>
  )
}

export default Home
